# build
markdown: kramdown
permalink: /blog/:year/:title/
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  domain: mattconn.io
  name: MattConn.io
  description: Matt's Development Blog
  author:
    name: Matthew Connelly
    url: http://mattconn.io/
  lang: en
  favicons:
    - /assets/tux_favicon.ico
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      - name: Github
        url: https://github.com/mattConn
      - name: Codepen
        url: http://codepen.io/mattconn
      - name: Gists
        url: https://gist.github.com/mattConn
      - name: Twitter
        url: https://twitter.com/matterialdesign
      - name: LinkedIn
        url: https://www.linkedin.com/in/matconn/
  external: http://thecharlesnyc.com 
